config/routes.rb
Rails.application.routes.draw do

  resources :days, only: :show

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#kalender'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/day.rb
class Day < ActiveRecord::Base
  validates :date, presence: true, uniqueness: true
  has_many :prizes
  has_many :kalenders, through: :prizes
  has_many :sponsors,  through: :prizes

  scope :year, ->(year) {
    where('EXTRACT(YEAR FROM days.date) = :year', year: year)
  }

  scope :opened, -> {
    if ENV['ALL_DOORS_OPEN'] && ENV['ALL_DOORS_OPEN'] == 'true'
      where(nil)
    else
      where('date <= ?', Time.now.in_time_zone('Berlin').to_date)
    end
  }
  attr_accessor :width, :height, :image, :position, :rowspan

  def name
    date.to_s
  end

  def self.create_for_year(year)
    start_date = Date.parse("01.12.#{year}")
    end_date   = Date.parse("24.12.#{year}")
    (start_date..end_date).each do |date|
      Day.where(date: date).first_or_create
    end
  end

  def year
    date.year
  end
end

app/models/importer.rb
# encoding: utf-8
class Importer
  CSV_HEADER = {
    day: "Tag",
    sponsor: {
      name: "Sponsor",
      person: "Ansprechpartner",
      address: "Straße/Hausnummer",
      city: "PLZ/Ort",
      phone: "Tel.",
      fax: "FAX",
      email: "email"
    },
    prize: {
      name: "Preis",
      anzahl: "Anzahl",
      cost: "Einzelpreis",
      lions_member: "LIONS-Mitglied"
    }
  }

  def self.import(year)
    file_path = Rails.root.join("kalender/#{year}.csv")
    new(file_path, year).perform!
  end

  def initialize(file_path, year)
    @year = year
    @csv = CSV.read file_path, headers: true, col_sep: ';', encoding: 'utf-8'
  end

  def self.copy_logos!(year)
    Sponsor.where(year: year, logo: nil).each(&:copy_logo!)
  end

  def perform!
    create_sponsors!
    create_prizes!
  end

  def create_sponsors!
    @csv.each do |row|
      sponsor_attributes = row_to_attributes row, header: CSV_HEADER[:sponsor]
      sponsor = Sponsor.where(
        year: @year,
        name: sponsor_attributes[:name]
      ).first_or_initialize
      sponsor.attributes = sponsor_attributes
      if sponsor.save
        puts sponsor_attributes[:name] + " created/updated (ID: #{sponsor.id})"
      else
        puts "error: #{sponsor.errors.full_messages.to_sentence}"
        binding.pry
      end
    end
  end

  def create_prizes!
    @csv.each do |row|
      prize_attributes = row_to_attributes row, header: CSV_HEADER[:prize]
      prize_attributes.merge! day: row_to_day(row), sponsor: row_to_sponsor(row)
      prize = Prize.where(
        sponsor: prize_attributes[:sponsor],
        name: prize_attributes[:name],
        day: prize_attributes[:day]
      ).first_or_create
      prize.update_attributes(prize_attributes)
      puts prize_attributes[:name] + " created/updated (ID: #{prize.id})"
    end
  end

  def row_to_attributes(row, header:)
    header.each_with_object({}) do |(key, column_name), hash|
      hash[key] = row[column_name]
    end
  end

  def row_to_day(row)
    date = Date.parse("#{row[CSV_HEADER[:day]]}.12.#{@year}")
    Day.find_by!(date: date)
  end

  def row_to_sponsor(row)
    sponsor_attributes = row_to_attributes row, header: CSV_HEADER[:sponsor]
    Sponsor.find_by!(year: @year, name: sponsor_attributes[:name])
  end
end

app/models/kalender.rb
class Kalender < ActiveRecord::Base
  validates :number, presence: true
  belongs_to :prize

  scope :year, ->(year) {
    joins(prize: :day).
      where('EXTRACT(YEAR FROM days.date) = :year', year: year)
  }

  delegate :sponsor, :day, :year, to: :prize
end

app/models/prize.rb
class Prize < ActiveRecord::Base
  validates :sponsor, :day, :name, presence: true

  belongs_to :sponsor
  belongs_to :day

  has_many :kalenders

  scope :year, ->(year) {
    joins(:day).
      where('EXTRACT(YEAR FROM days.date) = :year', year: year)
  }


  accepts_nested_attributes_for :kalenders

  delegate :year, to: :day

  def display_name
    [
      day.try(:name),
      sponsor.try(:name),
      name
    ].compact.join(' - ')
  end
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  validates :name, :address, :city, :phone, :year, presence: true

  mount_uploader :logo, LogoUploader
  has_many :prizes, dependent: :destroy

  def copy_logo!
    old_sponsor = Sponsor.
                  where.not(year: year, logo: nil).
                  where('name LIKE ?', '%' + name + '%').
                  first
    return unless old_sponsor
    self.remote_logo_url = old_sponsor.logo.url
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def show
    @day = Day.year(ENV['YEAR']).opened.find(params[:id])
    respond_to do |format|
      format.js
      format.html
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def placeholder
  end

  def kalender
    @days = Day.year(ENV['YEAR'])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_winner_collection?
    Date.today > Date.parse("24.12.#{ENV['YEAR']}")
  end
end

app/helpers/day_helper.rb
module DayHelper
  BOLD_DAYS     = [24]
  DARKENED_DAYS = [1, 20, 7, 4, 16, 13, 17, 23, 10, 15, 19, 3, 22]

  def day_box(image: nil, date: nil, height: nil, width: nil, rowspan: nil)
    date = Date.parse(date)
    if day = Day.year(ENV['YEAR']).opened.find_by(date: date)
      day.image = image
      day.height = height
      day.width = width
      day.rowspan = rowspan
      render day
    else
      content_tag 'td', rowspan: rowspan, class: 'disabled', :"data-until" => (date - Date.today).to_i do
        safe_join [
          date_on_door(date),
          image_tag(image, height: height, width: width)
        ]
      end
    end
  end

  def zindex_from_filename(filename)
    1000 - filename.match(/(\d\d\d?)\.gif/)[1].to_i
  end

  def date_on_door(date)
    day = date.day
    klass = ['date-on-door']
    klass << 'bold' if day.in? BOLD_DAYS
    klass << 'darken' if day.in? DARKENED_DAYS
    content_tag('div', day, class: klass)
  end

  def kalender_numbers(numbers)
    numbers.sort.map do |number|
      content_tag('span', number, class: 'prize-number')
    end.join(', ').html_safe
  end

  def sponsor_contact(sponsor)
    contact = "Abzuholen bei: "
    contact += [content_tag('b', sponsor.name),
                sponsor.address,
                sponsor.city,
                "Tel.: #{sponsor.phone}"].join(", ")
    if sponsor.person.present?
      contact += ";<br>Ihr Ansprechpartner: #{sponsor.person}"
    end
    contact.html_safe
  end
end

app/views/days/_day.html.slim
= content_tag 'td', class: 'opened', rowspan: day.rowspan do
  = link_to day_path(:id => day.id), :remote => true, class: 'item', style: "height: #{day.height}px; width: #{day.width}px; z-index: #{zindex_from_filename(day.image)}" do
    .info-wrap style="height: #{day.height}px; width: #{day.width}px;"
      .info-opened style= "height: #{day.height}px; width: #{day.width}px;"
        h3= day.date.day
        .info-opened-action
          button class='info-opened-day-winners' Gewinner anzeigen
      .info style="height: #{day.height}px; width: #{day.width}px;"
        .info-front
          = date_on_door(day.date)
          = image_tag(day.image, height: day.height, width: day.width)
        .info-back
          .info-back-sponsors
            - day.sponsors.uniq.each do |sponsor|
              - if sponsor.logo.present?
                = image_tag(sponsor.logo.url(:thumb))

app/views/days/_day_detail.html.slim
h1#day-date= day.date.strftime('%d.%m.%y')
ul#winners
  - @day.prizes.each do |prize|
    li#winners-item
      p
        span.prize-name
          = prize.name
        span.prize-meta
          - if prize.kalenders.count > 1
            = " haben die Kalender mit den Nummern "
          - else
            = " hat der Kalender mit der Nummer "
        = kalender_numbers(prize.kalenders.map(&:number))
        span.prize-meta= " gewonnen."
      p
        i= sponsor_contact(prize.sponsor)

ul#sponsors
  - perc = [(100 / @day.sponsors.uniq.count).round, 30].min
  - remainer = 100 - (perc * @day.sponsors.uniq.count)
  - if remainer > 5
    li#sponsor-item style="width: #{ remainer / 2 }%"
  - @day.sponsors.uniq.each do |sponsor|
    li#sponsor-item style="background-image: url(#{ sponsor.logo.url(:prize) }); width: #{ perc }%"
  - if remainer > 5
    li#sponsor-item style="width: #{ remainer / 2 }%"

app/views/days/show.html.slim
#calendar_wrapper
  #day.revealed
    = link_to 'X', root_path, id: "day-close"
    = render partial: 'day_detail', locals: { day: @day }

app/views/days/show.js.erb
 $("#day-winners").html("<%= escape_javascript(render partial: 'day_detail', locals: { day: @day } ) %>");
 $('#kalender, #sponsoren_wrapper').fadeOut(function(){
   $('#day').fadeIn();
 });

app/views/home/_winners.html.slim
#all-winners-wrapper
  table#all-winners
    thead
      tr
        th Kalender
        th Preis
    tbody
      - Kalender.year(ENV['YEAR']).order(number: :asc).each do |kalender|
        tr
          td.number= kalender.number
          td.prize
            = kalender.prize.name
            p
              i= sponsor_contact(kalender.prize.sponsor)

app/views/home/index.html.erb
<div id="calendar_wrapper">
  <div id="calendar">
    <%= image_tag('adventskalender.jpg', id: 'placeholder') %>
    <p id="description">Ab 1. Dezember sehen Sie hier den Lions Adventskalender 2014.
      <%= image_tag('logo.png', id: 'logo') %></p>
  </div>
</div>

app/views/home/kalender.html.slim
#calendar_wrapper
  #day
    #day-close
      | X
    #day-winners

  table#kalender cellpadding="0" cellspacing="0"
    = render partial: "home/kalenders/kalender_#{ ENV['YEAR'] }"

#sponsoren_wrapper
  = image_tag "kalenders/#{ENV['YEAR']}/sponsoren.jpg"

- if display_winner_collection?
  = render partial: 'winners'

app/views/home/kalenders/_kalender_2014.html.slim
tr
  td colspan="13"
    = image_tag('kalenders/2014/slices/kalender_front_01.jpg', height: 78, width: 920)
tr
  td rowspan="8"
    = image_tag('kalenders/2014/slices/kalender_front_02.jpg', height: 543, width: 88)
  = day_box(image: 'kalenders/2014/slices/kalender_front_03.jpg',
            date: "21.12.2014",
            height: 119,
            width: 119)
  td rowspan="8"
    = image_tag('kalenders/2014/slices/kalender_front_04.jpg', height: 543, width: 26)
  = day_box(image: 'kalenders/2014/slices/kalender_front_05.jpg',
            date: "15.12.2014",
            height: 119,
            width: 119,)
  td rowspan="8"
    = image_tag('kalenders/2014/slices/kalender_front_06.jpg', height: 543, width: 22)
  = day_box(image: 'kalenders/2014/slices/kalender_front_07.jpg',
            date: "11.12.2014",
            height: 119,
            width: 120)
  td rowspan="8"
    = image_tag('kalenders/2014/slices/kalender_front_08.jpg', height: 543, width: 23)
  = day_box(image: 'kalenders/2014/slices/kalender_front_09.jpg',
            date: "17.12.2014",
            height: 119,
            width: 119)
  td rowspan="8"
    = image_tag('kalenders/2014/slices/kalender_front_10.jpg', height: 543, width: 24)
  = day_box(image: 'kalenders/2014/slices/kalender_front_11.jpg',
            date: "23.12.2014",
            height: 119,
            width: 119)
  td rowspan="8"
    = image_tag('kalenders/2014/slices/kalender_front_12.jpg', height: 543, width: 17)
  = day_box(image: 'kalenders/2014/slices/kalender_front_13.jpg',
            date: "6.12.2014",
            height: 119,
            width: 119)
  td rowspan="8"
    = image_tag('kalenders/2014/slices/kalender_front_14.jpg', height: 543, width: 5)
tr
  td
    = image_tag('kalenders/2014/slices/kalender_front_15.jpg', height: 8, width: 119)
  td
    = image_tag('kalenders/2014/slices/kalender_front_16.jpg', height: 8, width: 119)
  td
    = image_tag('kalenders/2014/slices/kalender_front_17.jpg', height: 8, width: 120)
  td
    = image_tag('kalenders/2014/slices/kalender_front_18.jpg', height: 8, width: 119)
  td
    = image_tag('kalenders/2014/slices/kalender_front_19.jpg', height: 8, width: 119)
  td
    = image_tag('kalenders/2014/slices/kalender_front_20.jpg', height: 8, width: 119)
tr
  = day_box(image: 'kalenders/2014/slices/kalender_front_21.jpg',
            date: "7.12.2014",
            height: 119,
            width: 119)
  = day_box(image: 'kalenders/2014/slices/kalender_front_22.jpg',
            date: "12.12.2014",
            height: 119,
            width: 119)
  = day_box(image: 'kalenders/2014/slices/kalender_front_23.jpg',
            date: "2.12.2014",
            height: 119,
            width: 120)
  = day_box(image: 'kalenders/2014/slices/kalender_front_24.jpg',
            date: "22.12.2014",
            height: 119,
            width: 119)
  = day_box(image: 'kalenders/2014/slices/kalender_front_25.jpg',
            date: "8.12.2014",
            height: 119,
            width: 119)
  = day_box(image: 'kalenders/2014/slices/kalender_front_26.jpg',
            date: "14.12.2014",
            height: 119,
            width: 119)
tr
  td
    = image_tag('kalenders/2014/slices/kalender_front_27.jpg', height: 16, width: 119)
  td
    = image_tag('kalenders/2014/slices/kalender_front_28.jpg', height: 16, width: 119)
  td
    = image_tag('kalenders/2014/slices/kalender_front_29.jpg', height: 16, width: 120)
  td
    = image_tag('kalenders/2014/slices/kalender_front_30.jpg', height: 16, width: 119)
  td
    = image_tag('kalenders/2014/slices/kalender_front_31.jpg', height: 16, width: 119)
  td
    = image_tag('kalenders/2014/slices/kalender_front_32.jpg', height: 16, width: 119)
tr
  = day_box(image: 'kalenders/2014/slices/kalender_front_33.jpg',
            date: "20.12.2014",
            height: 119,
            width: 119)
  = day_box(image: 'kalenders/2014/slices/kalender_front_34.jpg',
            date: "4.12.2014",
            height: 119,
            width: 119)
  = day_box(image: 'kalenders/2014/slices/kalender_front_35.jpg',
            date: "24.12.2014",
            height: 119,
            width: 120)
  = day_box(image: 'kalenders/2014/slices/kalender_front_36.jpg',
            date: "3.12.2014",
            height: 119,
            width: 119)
  = day_box(image: 'kalenders/2014/slices/kalender_front_37.jpg',
            date: "10.12.2014",
            height: 119,
            width: 119)
  = day_box(image: 'kalenders/2014/slices/kalender_front_38.jpg',
            date: "18.12.2014",
            height: 119,
            width: 119)
tr
  td
    = image_tag('kalenders/2014/slices/kalender_front_39.jpg', height: 12, width: 119)
  td
    = image_tag('kalenders/2014/slices/kalender_front_40.jpg', height: 12, width: 119)
  td
    = image_tag('kalenders/2014/slices/kalender_front_41.jpg', height: 12, width: 120)
  td
    = image_tag('kalenders/2014/slices/kalender_front_42.jpg', height: 12, width: 119)
  td
    = image_tag('kalenders/2014/slices/kalender_front_43.jpg', height: 12, width: 119)
  td
    = image_tag('kalenders/2014/slices/kalender_front_44.jpg', height: 12, width: 119)
tr
  = day_box(image: 'kalenders/2014/slices/kalender_front_45.jpg',
            date: "9.12.2014",
            height: 120,
            width: 119)
  = day_box(image: 'kalenders/2014/slices/kalender_front_46.jpg',
            date: "19.12.2014",
            height: 120,
            width: 119)
  = day_box(image: 'kalenders/2014/slices/kalender_front_47.jpg',
            date: "5.12.2014",
            height: 120,
            width: 120)
  = day_box(image: 'kalenders/2014/slices/kalender_front_48.jpg',
            date: "13.12.2014",
            height: 120,
            width: 119)
  = day_box(image: 'kalenders/2014/slices/kalender_front_49.jpg',
            date: "16.12.2014",
            height: 120,
            width: 119)
  = day_box(image: 'kalenders/2014/slices/kalender_front_50.jpg',
            date: "1.12.2014",
            height: 120,
            width: 119)
tr
  td
    = image_tag('kalenders/2014/slices/kalender_front_51.jpg', height: 30, width: 119)
  td
    = image_tag('kalenders/2014/slices/kalender_front_52.jpg', height: 30, width: 119)
  td
    = image_tag('kalenders/2014/slices/kalender_front_53.jpg', height: 30, width: 120)
  td
    = image_tag('kalenders/2014/slices/kalender_front_54.jpg', height: 30, width: 119)
  td
    = image_tag('kalenders/2014/slices/kalender_front_55.jpg', height: 30, width: 119)
  td
    = image_tag('kalenders/2014/slices/kalender_front_56.jpg', height: 30, width: 119)

app/views/home/kalenders/_kalender_2015.html.slim
tr
  td colspan="13"
    = image_tag('kalenders/2015/slices/kalender_01.jpg', height: 25, width: 921)
tr
  td rowspan="8"
    = image_tag('kalenders/2015/slices/kalender_02.jpg', height: 596, width: 44)
  = day_box(image: 'kalenders/2015/slices/kalender_03.jpg', date:"21.12.2015", height: 112, width: 123)
  td rowspan="8"
    = image_tag('kalenders/2015/slices/kalender_04.jpg', height: 596, width: 20)
  = day_box(image: 'kalenders/2015/slices/kalender_05.jpg', date:"15.12.2015", height: 112, width: 121)
  td rowspan="8"
    = image_tag('kalenders/2015/slices/kalender_06.jpg', height: 596, width: 20)
  = day_box(image: 'kalenders/2015/slices/kalender_07.jpg', date:"11.12.2015", height: 112, width: 122)
  td rowspan="8"
    = image_tag('kalenders/2015/slices/kalender_08.jpg', height: 596, width: 20)
  = day_box(image: 'kalenders/2015/slices/kalender_09.jpg', date:"17.12.2015", height: 112, width: 122)
  td rowspan="8"
    = image_tag('kalenders/2015/slices/kalender_10.jpg', height: 596, width: 19)
  = day_box(image: 'kalenders/2015/slices/kalender_11.jpg', date:"23.12.2015", height: 112, width: 122)
  td rowspan="8"
    = image_tag('kalenders/2015/slices/kalender_12.jpg', height: 596, width: 20)
  = day_box(image: 'kalenders/2015/slices/kalender_13.jpg', date:"6.12.2015", height: 112, width: 122)
  td rowspan="8"
    = image_tag('kalenders/2015/slices/kalender_14.jpg', height: 596, width: 46)
tr
  td
    = image_tag('kalenders/2015/slices/kalender_15.jpg', height: 19, width: 123)
  td
    = image_tag('kalenders/2015/slices/kalender_16.jpg', height: 19, width: 121)
  td
    = image_tag('kalenders/2015/slices/kalender_17.jpg', height: 19, width: 122)
  td
    = image_tag('kalenders/2015/slices/kalender_18.jpg', height: 19, width: 122)
  td
    = image_tag('kalenders/2015/slices/kalender_19.jpg', height: 19, width: 122)
  td
    = image_tag('kalenders/2015/slices/kalender_20.jpg', height: 19, width: 122)
tr
  = day_box(image: 'kalenders/2015/slices/kalender_21.jpg', date:"7.12.2015", height: 111, width: 123)
  = day_box(image: 'kalenders/2015/slices/kalender_22.jpg', date:"12.12.2015", height: 111, width: 121)
  = day_box(image: 'kalenders/2015/slices/kalender_23.jpg', date:"2.12.2015", height: 111, width: 122)
  = day_box(image: 'kalenders/2015/slices/kalender_24.jpg', date:"22.12.2015", height: 111, width: 122)
  = day_box(image: 'kalenders/2015/slices/kalender_25.jpg', date:"8.12.2015", height: 111, width: 122)
  = day_box(image: 'kalenders/2015/slices/kalender_26.jpg', date:"14.12.2015", height: 111, width: 122)
tr
  td
    = image_tag('kalenders/2015/slices/kalender_27.jpg', height: 19, width: 123)
  td
    = image_tag('kalenders/2015/slices/kalender_28.jpg', height: 19, width: 121)
  td
    = image_tag('kalenders/2015/slices/kalender_29.jpg', height: 19, width: 122)
  td
    = image_tag('kalenders/2015/slices/kalender_30.jpg', height: 19, width: 122)
  td
    = image_tag('kalenders/2015/slices/kalender_31.jpg', height: 19, width: 122)
  td
    = image_tag('kalenders/2015/slices/kalender_32.jpg', height: 19, width: 122)
tr
  = day_box(image: 'kalenders/2015/slices/kalender_33.jpg', date:"20.12.2015", height: 112, width: 123)
  = day_box(image: 'kalenders/2015/slices/kalender_34.jpg', date:"4.12.2015", height: 112, width: 121)
  = day_box(image: 'kalenders/2015/slices/kalender_35.jpg', date:"24.12.2015", height: 112, width: 122)
  = day_box(image: 'kalenders/2015/slices/kalender_36.jpg', date:"3.12.2015", height: 112, width: 122)
  = day_box(image: 'kalenders/2015/slices/kalender_37.jpg', date:"10.12.2015", height: 112, width: 122)
  = day_box(image: 'kalenders/2015/slices/kalender_38.jpg', date:"18.12.2015", height: 112, width: 122)
tr
  td
    = image_tag('kalenders/2015/slices/kalender_39.jpg', height: 19, width: 123)
  td
    = image_tag('kalenders/2015/slices/kalender_40.jpg', height: 19, width: 121)
  td
    = image_tag('kalenders/2015/slices/kalender_41.jpg', height: 19, width: 122)
  td
    = image_tag('kalenders/2015/slices/kalender_42.jpg', height: 19, width: 122)
  td
    = image_tag('kalenders/2015/slices/kalender_43.jpg', height: 19, width: 122)
  td
    = image_tag('kalenders/2015/slices/kalender_44.jpg', height: 19, width: 122)
tr
  = day_box(image: 'kalenders/2015/slices/kalender_45.jpg', date:"9.12.2015", height: 112, width: 123)
  = day_box(image: 'kalenders/2015/slices/kalender_46.jpg', date:"19.12.2015", height: 112, width: 121)
  = day_box(image: 'kalenders/2015/slices/kalender_47.jpg', date:"5.12.2015", height: 112, width: 122)
  = day_box(image: 'kalenders/2015/slices/kalender_48.jpg', date:"13.12.2015", height: 112, width: 122)
  = day_box(image: 'kalenders/2015/slices/kalender_49.jpg', date:"16.12.2015", height: 112, width: 122)
  = day_box(image: 'kalenders/2015/slices/kalender_50.jpg', date:"1.12.2015", height: 112, width: 122)
tr
  td
    = image_tag('kalenders/2015/slices/kalender_51.jpg', height: 92, width: 123)
  td
    = image_tag('kalenders/2015/slices/kalender_52.jpg', height: 92, width: 121)
  td
    = image_tag('kalenders/2015/slices/kalender_53.jpg', height: 92, width: 122)
  td
    = image_tag('kalenders/2015/slices/kalender_54.jpg', height: 92, width: 122)
  td
    = image_tag('kalenders/2015/slices/kalender_55.jpg', height: 92, width: 122)
  td
    = image_tag('kalenders/2015/slices/kalender_56.jpg', height: 92, width: 122)

app/views/home/placeholder.html.erb
<div id="calendar_wrapper">
  <div id="calendar">
    <%= image_tag("kalenders/#{ENV['YEAR']}/adventskalender.jpg", id: 'placeholder') %>
    <p id="description">Ab 1. Dezember sehen Sie hier den Lions Adventskalender <%= ENV['YEAR'] %>.
      <%= image_tag('logo.png', id: 'logo') %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Lions Adventskalender</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/notifications/sponsor_information.html.erb
<h1>Notifications#sponsor_information</h1>

<p>
  Hello find me in app/views/notifications/sponsor_information.html.erb
</p>

app/views/notifications/sponsor_information.text.erb
Notifications#sponsor_information

Hello, find me in app/views/notifications/sponsor_information.text.erb